const ORDER_STATUS = {
    PENDING: 'PENDING',
    CONFIRMED: 'CONFIRMED',
    PREPARING: 'PREPARING',
    READY_FOR_PICKUP: 'READY_FOR_PICKUP',
    OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
    DELIVERED: 'DELIVERED',
    CANCELLED: 'CANCELLED',
    FAILED: 'FAILED',
};

const PAYMENT_STATUS = {
    PENDING: 'PENDING',
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED',
}

const DELIVERY_STATUS = {
    PENDING_ASSIGNMENT: 'PENDING_ASSIGNMENT',
    ACCEPTED: 'ACCEPTED', // Rider accepted
    PICKED_UP: 'PICKED_UP',
    DELIVERED: 'DELIVERED',
    FAILED_DELIVERY: 'FAILED_DELIVERY',
}

module.exports = {
    ORDER_STATUS,
    PAYMENT_STATUS,
    DELIVERY_STATUS
};