# k8s/order-service/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: uberx-payment # <--- UPDATED NAMESPACE
spec:
  selector:
    app: payment-service
  ports:
  - port: 4006
    targetPort: 4006
  type: ClusterIP