# k8s/uberx-gateway/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: uberx-gateway
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        # --- UPDATE THIS LINE ---
        image: thusalapi/nginx # Use the custom image built by Skaffold
        # --- END UPDATE ---
        ports:
        - containerPort: 80
        volumeMounts:
        # --- REMOVE VOLUME MOUNT FOR NGINX CONFIG ---
        # The config is now BAKED INTO the image via the Dockerfile's COPY command,
        # so we don't need to mount it from the ConfigMap anymore.
        # - name: nginx-config
        #   mountPath: /etc/nginx/conf.d/default.conf
        #   subPath: nginx.conf
        # --- END REMOVAL ---
        resources:
          limits:
            cpu: "0.2"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health # Assumes /health is defined in your nginx.conf
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health # Assumes /health is defined in your nginx.conf
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 2
      # --- REMOVE VOLUME DEFINITION FOR NGINX CONFIG ---
      # volumes:
      # - name: nginx-config
      #   configMap:
      #     name: nginx-config # Reference to the ConfigMap in uberx-gateway ns
      # --- END REMOVAL ---