# k8s/nginx/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: uberx-gateway # <--- UPDATED NAMESPACE
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer # Keep LoadBalancer for external access