# k8s/uberx-order/mysql-order-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-promotion # Service for Order DB within the order namespace
  namespace: uberx-promotion # <--- UPDATED NAMESPACE
spec:
  selector:
    app: mysql-promotion
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP