apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: uberx-nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: nats:2.10.22
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 8222
          name: monitoring
        command: 
          - "/nats-server"
          - "--jetstream"
          - "--http_port=8222"
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: uberx-nats
spec:
  selector:
    app: nats
  ports:
  - name: client
    port: 4222
    targetPort: client
  - name: monitoring
    port: 8222
    targetPort: monitoring