# k8s/order-service/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: uberx
spec:
  selector:
    app: order-service
  ports:
  - port: 4001
    targetPort: 4001
  type: ClusterIP
