apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-auth # Deployment for the Authentication DB
  namespace: uberx-auth
  labels:
    app: mysql-auth
spec:
  replicas: 1 # Ensure only one replica when using ReadWriteOnce PVs
  selector:
    matchLabels:
      app: mysql-auth
  strategy:
    type: Recreate # Recreate strategy is safer for stateful apps like DBs with RWO volumes
  template:
    metadata:
      labels:
        app: mysql-auth
    spec:
      containers:
      - image: mysql:8.0
        name: mysql-auth # Container name
        env:
        # Use the shared secret for auth DB credentials within this namespace
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: root-password
        - name: MYSQL_DATABASE # Default database to create on startup
          value: auth_db
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-auth-persistent-storage # Mount the persistent storage volume
          mountPath: /var/lib/mysql
        - name: mysql-auth-init-scripts # Mount the initialization scripts volume
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-auth-persistent-storage # Define the volume using the PVC
        persistentVolumeClaim:
          claimName: mysql-auth-pv-claim # Reference the PVC for auth DB
      - name: mysql-auth-init-scripts # Define the volume using the ConfigMap
        configMap:
          name: mysql-auth-init-scripts # Reference the ConfigMap for auth DB init scripts