# k8s/uberx-db/mysql-auth-init-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-auth-init-scripts # ConfigMap holding init SQL for Auth DB
  namespace: uberx-auth
data:
  init_auth.sql: | # Script filename executed by mysql entrypoint
    CREATE DATABASE IF NOT EXISTS auth_db;
    USE auth_db;

    CREATE TABLE IF NOT EXISTS users (
        id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(50) NOT NULL UNIQUE,
        email VARCHAR(100) NOT NULL UNIQUE,
        password VARCHAR(255) NOT NULL,
        first_name VARCHAR(50),
        last_name VARCHAR(50),
        -- Add other user fields from ERD if managed by auth service
        -- role VARCHAR(20) DEFAULT 'customer',
        -- address VARCHAR(255),
        -- phone VARCHAR(20),
        is_active BOOLEAN DEFAULT TRUE,
        is_verified BOOLEAN DEFAULT FALSE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS refresh_tokens (
        id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        userId INT UNSIGNED NOT NULL,
        token VARCHAR(500), # Raw token (consider if needed)
        token_hash VARCHAR(255) NOT NULL, # Hashed token for lookups
        expires_at TIMESTAMP NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        is_revoked BOOLEAN DEFAULT FALSE,
        UNIQUE KEY unique_token (token_hash),
        FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
    );