# k8s/uberx-order/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: uberx-order # <--- Correct namespace
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: sachilaawandya/order-service:latest
        ports:
        - containerPort: 4001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "4001"
        - name: DB_HOST
          # Connect to DB service in the same namespace
          value: "mysql-order" # <--- UPDATED HOST
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              # Secret is in the same namespace
              name: mysql-order-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              # Secret is in the same namespace
              name: mysql-order-credentials
              key: password
        - name: DB_NAME
          value: "order_db"
        - name: ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: access-token-secret
        # ... resources, probes ...
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 4001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 4001
          initialDelaySeconds: 5
          periodSeconds: 5